### ISSUE TITLE
Connect first map with "Fascia di età" and "Gender"

### ISSUE THREAD

**Issue by sebbalex** [italia/covid19-dashboard-vaccini#33]
Clicking on first map should also update "Fascia di età" plot and "Gender" data filtering data of selected region.

**Comment by libremente** [comment]
The connection makes sense, however I don't really like the fact that whenever a region gets selected the table collapses and the whole layout "moves up". 
Since we know that we can select just one region per time (so, after the filter is applied, the resulting table won't be any larger than 1 row) I believe we should find a better way of handling it. WDYT @sebbalex?

**Comment by sebbalex** [comment]
Yeah, I'm totally with you, this breaks the entire page layout.
note: resulting table can be larger than one item by typing directly in search box.

**Comment by bfabio** [comment]
Looks like this is fixed in the official dashboard at https://github.com/italia/report-vaccini-anti-covid-19/.
